In [26]:
import pandas as pd
import numpy as np

In [5]:


# 创建示例数据
data = {
    '商品ID': ['P001', 'P002', 'P003', 'P004', 'P005'],
    '商品类别': ['电子产品', '服装', '食品', '电子产品', '服装'],
    '一月销量': [120, 85, 150, 90, 110],
    '二月销量': [135, 95, 160, 80, 120],
    '三月销量': [140, 100, 170, 95, 130]
}

# 创建DataFrame，设置商品ID为索引
sales_df = pd.DataFrame(data).set_index('商品ID')
sales_df

      商品类别  一月销量  二月销量  三月销量
商品ID
P001  电子产品   120   135   140
P002    服装    85    95   100
P003    食品   150   160   170
P004  电子产品    90    80    95
P005    服装   110   120   130

In [4]:
# 查看数据集行数和列数
sales_df.shape

(5, 4)

In [10]:
# 获取所有商品 ID
sales_df.index.to_list()

['P001', 'P002', 'P003', 'P004', 'P005']

In [14]:
print(sales_df.iloc[:, :0])
# sales_df['商品类别']

Empty DataFrame
Columns: []
Index: [P001, P002, P003, P004, P005]

In [15]:
# 获取数据集所有值
sales_df.values

array([['电子产品', 120, 135, 140],
       ['服装', 85, 95, 100],
       ['食品', 150, 160, 170],
       ['电子产品', 90, 80, 95],
       ['服装', 110, 120, 130]], dtype=object)

In [16]:
# 获取所有列名
sales_df.columns

Index(['商品类别', '一月销量', '二月销量', '三月销量'], dtype='str')

In [17]:
# 转置数据集
sales_df.T

商品ID  P001 P002 P003  P004 P005
商品类别  电子产品   服装   食品  电子产品   服装
一月销量   120   85  150    90  110
二月销量   135   95  160    80  120
三月销量   140  100  170    95  130

In [18]:
# 获取前三条数据
sales_df.head(3)

      商品类别  一月销量  二月销量  三月销量
商品ID
P001  电子产品   120   135   140
P002    服装    85    95   100
P003    食品   150   160   170

In [19]:
# 获取后两条数据
sales_df.tail(2)

      商品类别  一月销量  二月销量  三月销量
商品ID
P004  电子产品    90    80    95
P005    服装   110   120   130

In [21]:
# 重置索引
sales_df.reset_index(drop=True)

   商品类别  一月销量  二月销量  三月销量
0  电子产品   120   135   140
1    服装    85    95   100
2    食品   150   160   170
3  电子产品    90    80    95
4    服装   110   120   130

In [24]:
# 以商品类别作为新的索引
sales_df.set_index('商品类别')

      一月销量  二月销量  三月销量
商品类别
电子产品   120   135   140
服装      85    95   100
食品     150   160   170
电子产品    90    80    95
服装     110   120   130

In [27]:
# 创建成绩数据（单位：分）
scores_data = {
    '学生ID': ['S001', 'S002', 'S003', 'S004', 'S005'],
    '数学': [85, 92, 76, 88, 95],
    '英语': [78, 85, 82, 90, 88],
    '物理': [90, 87, 91, 79, 83]
}

# 转换为ndarray（以学生ID为索引）
scores_ndarray = np.array([
    [85, 78, 90],
    [92, 85, 87],
    [76, 82, 91],
    [88, 90, 79],
    [95, 88, 83]
], dtype=np.float64)

# 设置学生ID为行索引（实际操作中可通过花式索引实现）
student_ids = np.array(['S001', 'S002', 'S003', 'S004', 'S005'])
subjects = np.array(['数学', '英语', '物理'])

In [28]:
# 查看成绩数组的维度、形状、元素类型及总个数
scores_ndarray.ndim

2

In [29]:
scores_ndarray.shape

(5, 3)

In [30]:
scores_ndarray.dtype

dtype('float64')

In [32]:
scores_ndarray.size

15

In [34]:
# 将成绩数组转换为整数类型，并查看每个元素的字节大小
scores_ndarray=scores_ndarray.astype(int)
scores_ndarray

array([[85, 78, 90],
       [92, 85, 87],
       [76, 82, 91],
       [88, 90, 79],
       [95, 88, 83]])

In [35]:
scores_ndarray.itemsize

8

In [ ]:
# 计算所有学生的数学平均分、物理总分及英语最高分
scores_ndarray.mean()

In [42]:
math_index=np.where(subjects=='数学')[0][0]

In [44]:
math_mean=np.mean(scores_ndarray[:,math_index])
print(math_mean)

87.2

In [47]:
math_mean=scores_ndarray[:,0]
math_mean.mean()

np.float64(87.2)

In [49]:
wuli_sum=scores_ndarray[:,-1]
wuli_sum.sum()

np.int64(430)

In [51]:
english_max=scores_ndarray[:,1]
english_max.max()

np.int64(90)

In [54]:
# 对物理成绩进行排序，并找到最低分的索引
wuli_sum.sort()
wuli_sum

array([79, 83, 87, 90, 91])

In [55]:
wuli_sum.argmin()

np.int64(0)

In [59]:
# 使用where函数将 90 分以上的成绩标记为 'A'，其余为 'B'
scores_ndarray
np.where(scores_ndarray>90, 'a' ,'b')

array([['b', 'b', 'b'],
       ['a', 'b', 'b'],
       ['b', 'b', 'b'],
       ['b', 'b', 'b'],
       ['a', 'b', 'a']], dtype='<U1')

In [63]:
scores_ndarray

array([[85, 78, 79],
       [92, 85, 83],
       [76, 82, 87],
       [88, 90, 90],
       [95, 88, 91]])

In [64]:
# 计算每个学生的总分（行方向求和）与每科的平均分（列方向求平均）
scores_ndarray[0,:].sum()
scores_ndarray[1,:].sum()
scores_ndarray[2,:].sum()
scores_ndarray[3,:].sum()
scores_ndarray[4,:].sum()

array([85, 78, 79])

In [ ]:
scores_ndarray[:,0]

In [62]:
# 使用cumsum计算每个学生的累计得分？
scores_ndarray.cumsum()[-1]

np.int64(1289)

In [61]:
scores_ndarray

array([[85, 78, 79],
       [92, 85, 83],
       [76, 82, 87],
       [88, 90, 90],
       [95, 88, 91]])