In [97]:

import pandas as pd

In [98]:
data = {
    "order_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "user_name": ["张三", "李四", "王五", "赵六", "钱七", "张三", "李四", "孙八"],
    "product": ["手机", "电脑", "耳机", "手机", "平板", "电脑", "耳机", "平板"],
    "price": [3999, 5999, 199, 3899, 2499, 5899, 189, 2399],
    "quantity": [1, 1, 2, 1, 1, 1, 3, 1],
    "pay_type": ["支付宝", "微信", "支付宝", "微信", "支付宝", "微信", "支付宝", "微信"]
}

df = pd.DataFrame(data)
df

   order_id user_name product  price  quantity pay_type
0      1001        张三      手机   3999         1      支付宝
1      1002        李四      电脑   5999         1       微信
2      1003        王五      耳机    199         2      支付宝
3      1004        赵六      手机   3899         1       微信
4      1005        钱七      平板   2499         1      支付宝
5      1006        张三      电脑   5899         1       微信
6      1007        李四      耳机    189         3      支付宝
7      1008        孙八      平板   2399         1       微信

In [99]:
# 1. 查看数据集前5行
#    知识点：head()
df.head()
# 1. 查看后3行
#    知识点：tail()
df.tail(3)
# 1. 获取 user_name 列（两种写法）
#    知识点：单列获取
df['user_name']
df.user_name
# 1. 获取 product、price 两列
#    知识点：多列获取
df[['product', 'price']]
# 1. 获取第2行到第4行
#    知识点：行切片
df.iloc[2:4, :]
# 1. 筛选 product == "手机"
#    知识点：布尔索引
df.query("product=='手机'")
df[df['product'] == '手机']
# 1. 筛选 price > 3000
#    知识点：数值筛选
df.query('price>3000')
# 1. 筛选 user_name == "张三"
#    知识点：精确匹配
df.query('user_name=="张三"')
# 1. 使用 query 筛选支付方式为微信
#    知识点：query
df.query('pay_type=="微信"')
# 1. 筛选产品为电脑且价格>5000
#    知识点：多条件与
df.query('product=="电脑"&price>5000')
df[(df['product']=='电脑')&(df['price']>5000)]
type(df['product']=='电脑')
type(df.product=='电脑')

bool

In [100]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   order_id   8 non-null      int64
 1   user_name  8 non-null      str
 2   product    8 non-null      str
 3   price      8 non-null      int64
 4   quantity   8 non-null      int64
 5   pay_type   8 non-null      str
dtypes: int64(3), str(3)
memory usage: 672.0 bytes

In [101]:
# 1. 新增 discount = 0.9
#    知识点：直接赋值新增列
df['discount']=0.9
df
# 1. 新增 total = price * quantity
#    知识点：列运算新增列
df['total']=df['price']*df['quantity']
df
# 1. assign 新增 tax = 0.06
#    知识点：assign
df=df.assign(tax=0.06)
df
# 1. assign 同时新增 mark=0、level="普通"
#    知识点：assign多列
df=df.assign(mark=0,level='普通')
df
# 1. 新增 is_expensive：≥3000为1，否则0
#    知识点：apply条件列
# df.apply(lambda is_expensive>=3000:1,0)
def fun(price):
    if price>=3000:
        return 1
    else:
        return 0

df['is_expensive'] = df['price'].apply(fun)
df
df['is_expensive']=df['price'].apply(lambda x:1 if x>=3000 else 0)
df
# 1. 新增 buy_num = [1,1,2,1,1,1,3,1]
#    知识点：列表赋值列
df['buy_num']=[1,1,2,1,1,1,3,1]
# 1. 新增 pay_month = "2026-04"
#    知识点：固定字符串列
df['pay_month']='2026-04'
# 1. assign 新增 final_price = total * discount
#    知识点：assign+运算
df=df.assign(final_price=df.total*df.discount)
# 1. 新增 product_type：手机/电脑为数码，其他为配件
#    知识点：自定义函数apply
df['product_type']=df['product'].apply(lambda x:'数码' if x=='手机'or x=='电脑' else '其他配件')
# 1. 复制 price 为 price_copy
#    知识点：复制列
df['price_copy']=df.price.copy()

In [118]:
# 1. 修改第0行 price 为 3999
#    知识点：loc单值修改
df.loc[0,'price']=3999
# 1. 把所有耳机的 price 改为 199
#    知识点：条件批量修改

# df['price']=df['product'].apply(lambda x:199 if x=='耳机')
# def fun(product):不对
#     if product=='耳机':
#         return 199
# df=df.assign(price=fun(df.product))
df.loc[df['product'] == '耳机', 'price'] = 199

# 1. replace 支付宝→AliPay
#    知识点：replace替换
# df.method({col: value}, inplace=True)
df.replace({'支付宝':'AliPay'},inplace=True)
# 1. replace 微信→WeChat，支付宝→AliPay
#    知识点：多值替换
df.replace({'支付宝':'AliPay1','微信':'WeChat'},inplace=True)
# 1. quantity 全部 +1
#    知识点：整列数值修改
df['quantity']=df['quantity']+1
# 1. 列名 pay_type → payment
#    知识点：rename
df.rename(columns={'pay_type':'payment'},inplace=True)
# 1. 订单1003的用户名改为小王
#    知识点：条件定位修改
df.loc[df['order_id']==1003,'user_name']='小王'
# 1. assign 覆盖 total = pricequantity0.95
#    知识点：assign覆盖列
df=df.assign(total=df['price']*df['quantity']*0.95)
# 1. quantity>2 标记 is_bulk=1
#    知识点：条件标记
df['is_bulk']=df['quantity'].apply(lambda x:1 if x>2 else 0)
# df['is]=df.loc[:,df['quantity'>2]]
# 1. 张三→张三丰
#    知识点：字符串replace
df.replace({'张三':'张三丰'},inplace=True)
df

,order_id,user_name,product,price,quantity,payment,discount,total,tax,mark,level,is_expensive,buy_num,pay_month,final_price,product_type,price_copy,username,is_bulk
0,1001,张三丰,手机,3999,17,AliPay,0.9,64583.85,0.06,0,普通,1,1,2026-04,3599.1,数码,3999,NaN,1
1,1002,李四,电脑,5999,17,WeChat,0.9,96883.85,0.06,0,普通,1,1,2026-04,5399.1,数码,5999,NaN,1
2,1003,小王,耳机,199,18,AliPay,0.9,3402.90,0.06,0,普通,0,2,2026-04,358.2,其他配件,199,小王,1
3,1004,赵六,手机,3899,17,WeChat,0.9,62968.85,0.06,0,普通,1,1,2026-04,3509.1,数码,3899,NaN,1
4,1005,钱七,平板,2499,17,AliPay,0.9,40358.85,0.06,0,普通,0,1,2026-04,2249.1,其他配件,2499,NaN,1
5,1006,张三丰,电脑,5899,17,WeChat,0.9,95268.85,0.06,0,普通,1,1,2026-04,5309.1,数码,5899,NaN,1
6,1007,李四,耳机,199,19,AliPay,0.9,3591.95,0.06,0,普通,0,3,2026-04,510.3,其他配件,189,NaN,1
7,1008,孙八,平板,2399,17,WeChat,0.9,38743.85,0.06,0,普通,0,1,2026-04,2159.1,其他配件,2399,NaN,1

In [137]:
# 1. 删除索引2的行
#    知识点：drop删行
# df.drop(2,inplace=True)
# 1. 删除索引0、3、5
#    知识点：drop多行
# df.drop([0,3,5],inplace=True)
# 1. 删除 discount 列
#    知识点：drop删列 axis=1
# df.drop(columns='discount',inplace=True)
# 1. del 删除 tax 列
#    知识点：del删列
# df.drop('tax',axis=1,inplace=True)
# 1. 删除 mark、level 两列
#    知识点：drop多列
# df.drop(['mark','level'],axis=1,inplace=True)
# 1. 查看 user_name 唯一值
#    知识点：unique
df.user_name.unique()
# 1. user_name 去重保留第一条
#    知识点：drop_duplicates
df.user_name.drop_duplicates(keep='first')
# 1. 按 user_name 对全表去重
#    知识点：df去重
#
# 1. 删除 price 列（两种方法）
#    知识点：drop vs del
#
# 1. 筛选 total 不为空的行
#    知识点：notnull
df.total.notnull()
df

,order_id,user_name,product,price,quantity,payment,total,is_expensive,buy_num,pay_month,final_price,product_type,price_copy,username,is_bulk
1,1002,李四,电脑,5999,17,WeChat,96883.85,1,1,2026-04,5399.1,数码,5999,NaN,1
4,1005,钱七,平板,2499,17,AliPay,40358.85,0,1,2026-04,2249.1,其他配件,2499,NaN,1
6,1007,李四,耳机,199,19,AliPay,3591.95,0,3,2026-04,510.3,其他配件,189,NaN,1
7,1008,孙八,平板,2399,17,WeChat,38743.85,0,1,2026-04,2159.1,其他配件,2399,NaN,1

In [119]:

df

,order_id,user_name,product,price,quantity,payment,discount,total,tax,mark,level,is_expensive,buy_num,pay_month,final_price,product_type,price_copy,username,is_bulk
0,1001,张三丰,手机,3999,17,AliPay,0.9,64583.85,0.06,0,普通,1,1,2026-04,3599.1,数码,3999,NaN,1
1,1002,李四,电脑,5999,17,WeChat,0.9,96883.85,0.06,0,普通,1,1,2026-04,5399.1,数码,5999,NaN,1
2,1003,小王,耳机,199,18,AliPay,0.9,3402.90,0.06,0,普通,0,2,2026-04,358.2,其他配件,199,小王,1
3,1004,赵六,手机,3899,17,WeChat,0.9,62968.85,0.06,0,普通,1,1,2026-04,3509.1,数码,3899,NaN,1
4,1005,钱七,平板,2499,17,AliPay,0.9,40358.85,0.06,0,普通,0,1,2026-04,2249.1,其他配件,2499,NaN,1
5,1006,张三丰,电脑,5899,17,WeChat,0.9,95268.85,0.06,0,普通,1,1,2026-04,5309.1,数码,5899,NaN,1
6,1007,李四,耳机,199,19,AliPay,0.9,3591.95,0.06,0,普通,0,3,2026-04,510.3,其他配件,189,NaN,1
7,1008,孙八,平板,2399,17,WeChat,0.9,38743.85,0.06,0,普通,0,1,2026-04,2159.1,其他配件,2399,NaN,1