In [1]:
import pandas as pd

In [52]:


# 模拟数据
data = {
    'movie_id': [1, 2, 3, 4, 5],
    'title': ['The Shawshank Redemption', 'The Godfather', 'Pulp Fiction', 'The Dark Knight', 'Forrest Gump'],
    'genre': ['Drama', 'Crime', 'Crime', 'Action', 'Drama'],
    'release_year': [1994, 1972, 1994, 2008, 1994],
    'rating': [9.3, 9.2, 8.9, 9.0, 8.8],
    'duration': [142, 175, 154, 152, 142]
}

df = pd.DataFrame(data)
df.to_csv('movies.csv', index=False)
df

   movie_id                     title   genre  release_year  rating  duration
0         1  The Shawshank Redemption   Drama          1994     9.3       142
1         2             The Godfather   Crime          1972     9.2       175
2         3              Pulp Fiction   Crime          1994     8.9       154
3         4           The Dark Knight  Action          2008     9.0       152
4         5              Forrest Gump   Drama          1994     8.8       142

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      5 non-null      int64
 1   title         5 non-null      str
 2   genre         5 non-null      str
 3   release_year  5 non-null      int64
 4   rating        5 non-null      float64
 5   duration      5 non-null      int64
dtypes: float64(1), int64(3), str(2)
memory usage: 474.0 bytes

In [4]:
df.shape

(5, 6)

In [5]:
df.columns

Index(['movie_id', 'title', 'genre', 'release_year', 'rating', 'duration'], dtype='str')

In [8]:
df.index.to_list()

[0, 1, 2, 3, 4]

In [9]:
df.title

0    The Shawshank Redemption
1               The Godfather
2                Pulp Fiction
3             The Dark Knight
4                Forrest Gump
Name: title, dtype: str

In [11]:
df.iloc[1,:]

movie_id                    2
title           The Godfather
genre                   Crime
release_year             1972
rating                    9.2
duration                  175
Name: 1, dtype: object

In [12]:
df.rating.head(3)

0    9.3
1    9.2
2    8.9
Name: rating, dtype: float64

In [13]:
df.release_year.tail(2)

3    2008
4    1994
Name: release_year, dtype: int64

In [15]:
df[df['rating']>9.0]
df.query('rating>9.0')

   movie_id                     title  genre  release_year  rating  duration
0         1  The Shawshank Redemption  Drama          1994     9.3       142
1         2             The Godfather  Crime          1972     9.2       175

In [16]:
df.query('release_year==1994')

   movie_id                     title  genre  release_year  rating  duration
0         1  The Shawshank Redemption  Drama          1994     9.3       142
2         3              Pulp Fiction  Crime          1994     8.9       154
4         5              Forrest Gump  Drama          1994     8.8       142

In [19]:
df.query("genre=='Crime'")
df[df['genre']=='Crime']

   movie_id          title  genre  release_year  rating  duration
1         2  The Godfather  Crime          1972     9.2       175
2         3   Pulp Fiction  Crime          1994     8.9       154

In [20]:
df.set_index('movie_id')

                             title   genre  release_year  rating  duration
movie_id
1         The Shawshank Redemption   Drama          1994     9.3       142
2                    The Godfather   Crime          1972     9.2       175
3                     Pulp Fiction   Crime          1994     8.9       154
4                  The Dark Knight  Action          2008     9.0       152
5                     Forrest Gump   Drama          1994     8.8       142

In [22]:
df.reset_index(drop=True)

   movie_id                     title   genre  release_year  rating  duration
0         1  The Shawshank Redemption   Drama          1994     9.3       142
1         2             The Godfather   Crime          1972     9.2       175
2         3              Pulp Fiction   Crime          1994     8.9       154
3         4           The Dark Knight  Action          2008     9.0       152
4         5              Forrest Gump   Drama          1994     8.8       142

In [24]:
print(type(df.rating))
df.rating.dtype

<class 'pandas.Series'>

dtype('float64')

In [25]:
df.dtypes

movie_id          int64
title               str
genre               str
release_year      int64
rating          float64
duration          int64
dtype: object

In [28]:
df.rating.sort_values()

4    8.8
2    8.9
3    9.0
1    9.2
0    9.3
Name: rating, dtype: float64

In [29]:
df.release_year.sort_values(ascending=False)

3    2008
0    1994
2    1994
4    1994
1    1972
Name: release_year, dtype: int64

In [30]:
df.rating.mean()

np.float64(9.040000000000001)

In [31]:
df.duration.max()

175

In [33]:
df.duration.min()

142

In [36]:

df.rating.median()

9.0

In [37]:
df.rating.std()

0.20736441353327703

In [38]:
df.genre.count()

np.int64(5)

In [39]:
df.describe()

       movie_id  release_year    rating    duration
count  5.000000      5.000000  5.000000    5.000000
mean   3.000000   1992.400000  9.040000  153.000000
std    1.581139     12.915107  0.207364   13.490738
min    1.000000   1972.000000  8.800000  142.000000
25%    2.000000   1994.000000  8.900000  142.000000
50%    3.000000   1994.000000  9.000000  152.000000
75%    4.000000   1994.000000  9.200000  154.000000
max    5.000000   2008.000000  9.300000  175.000000

In [43]:
df[['title','rating']]
df.loc[:,['title','rating']]
df.iloc[:,[1,4]]

                      title  rating
0  The Shawshank Redemption     9.3
1             The Godfather     9.2
2              Pulp Fiction     8.9
3           The Dark Knight     9.0
4              Forrest Gump     8.8

In [44]:
df.iloc[:,1:4]

                      title   genre  release_year
0  The Shawshank Redemption   Drama          1994
1             The Godfather   Crime          1972
2              Pulp Fiction   Crime          1994
3           The Dark Knight  Action          2008
4              Forrest Gump   Drama          1994

In [54]:
df['rating']=df['rating']+1

In [47]:
df.duration-10

0    132
1    165
2    144
3    142
4    132
Name: duration, dtype: int64

In [55]:
df.query('rating>9.5')

   movie_id                     title   genre  release_year  rating  duration
0         1  The Shawshank Redemption   Drama          1994    10.3       142
1         2             The Godfather   Crime          1972    10.2       175
2         3              Pulp Fiction   Crime          1994     9.9       154
3         4           The Dark Knight  Action          2008    10.0       152
4         5              Forrest Gump   Drama          1994     9.8       142

In [57]:
df.query('rating>9.5&release_year==1994')

   movie_id                     title  genre  release_year  rating  duration
0         1  The Shawshank Redemption  Drama          1994    10.3       142
2         3              Pulp Fiction  Crime          1994     9.9       154
4         5              Forrest Gump  Drama          1994     9.8       142

In [59]:
df['title'].str.contains('The')

0     True
1     True
2    False
3     True
4    False
Name: title, dtype: bool

In [60]:
df[df['title'].str.contains('The')]

   movie_id                     title   genre  release_year  rating  duration
0         1  The Shawshank Redemption   Drama          1994    10.3       142
1         2             The Godfather   Crime          1972    10.2       175
3         4           The Dark Knight  Action          2008    10.0       152

In [61]:
df.rating.head(3).reset_index()

   index  rating
0      0    10.3
1      1    10.2
2      2     9.9

In [62]:
df.rating.round(1)

0    10.3
1    10.2
2     9.9
3    10.0
4     9.8
Name: rating, dtype: float64

In [63]:
df.rating.cumsum()

0    10.3
1    20.5
2    30.4
3    40.4
4    50.2
Name: rating, dtype: float64

In [64]:
df.duration.cummax()

0    142
1    175
2    175
3    175
4    175
Name: duration, dtype: int64

In [65]:
df.to_csv('new_movies.csv',index=False)

In [66]:
s=df.rating

In [67]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [68]:
s.values

array([10.3, 10.2,  9.9, 10. ,  9.8])

In [69]:
s.info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: rating
Non-Null Count  Dtype
--------------  -----
5 non-null      float64
dtypes: float64(1)
memory usage: 172.0 bytes