In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False

In [ ]:
np.random.randint()

In [ ]:
arr=np.logspace(2,4,5)

In [ ]:

arr1=np.arange(1,13).reshape(3,4)
print(arr1)

In [ ]:
np.argmax(arr1)

In [ ]:
arr1=np.array([
    [1,2,1],
    [2,3,5]
])
print(arr1)

In [ ]:
arr2=np.unique(arr1)
print(arr2)

In [ ]:
arr2.sort()

In [ ]:
df=pd.read_csv('../data/1960-2019全球GDP数据.csv', encoding='gbk')
# print(type(df))
df

In [ ]:
china_df=df[df.country=='中国']
usa_df=df[df.country=='美国']
jp_df=df[df.country=='日本']
print(type(china_df))

In [ ]:
china_df.set_index('year',inplace=True)
usa_df.set_index('year',inplace=True)
jp_df.set_index('year',inplace=True)
china_df

In [ ]:
china_df.GDP.plot(legend='中国')
usa_df.GDP.plot(legend='美国')
jp_df.GDP.plot(legend='日本')

In [ ]:
china_df.rename(columns={'GDP':'china'},inplace=True)
usa_df.rename(columns={'GDP':'usa'},inplace=True)
jp_df.rename(columns={'GDP':'jp'},inplace=True)

In [ ]:
china_df.china.plot(legend='中国')
usa_df.usa.plot(legend='美国')
jp_df.jp.plot(legend='日本')

In [ ]:
china_df.rename(columns={'china':'中国'},inplace=True)
usa_df.rename(columns={'usa':'美国'},inplace=True)
jp_df.rename(columns={'jp':'日本'},inplace=True)

In [ ]:
china_df.中国.plot(legend='中国')
usa_df.美国.plot(legend='美国')
jp_df.日本.plot(legend='日本')

In [ ]:
my_list=[1,2,3,4]
s1=pd.Series(my_list)
s1

In [ ]:
s2=pd.Series([1,2,3,4],index=['a','b','c','d'])
s2

In [ ]:
s3=pd.Series((1,2,3,4))
s3

In [ ]:
s4=pd.Series({'a':1,'b':2})
s4

In [ ]:
s5=pd.Series(np.arange(5))
s5

In [ ]:
s5=pd.Series(np.arange(5),index=[f'zhangsan{i}' for i in range(5)])
s5

In [ ]:
info={
    "name":["11","222","33"],
    "gender":["man","man","man"],
    "age":[11,44,55]
}
df1=pd.DataFrame(data=info)
df1

In [ ]:
info=[
    ("222","sdfjsl",22),
    ("222","sdfjsl",22),
    ("222","sdfjsl",22)
]
df2=pd.DataFrame(info,columns=['xingming','sex','age'])
df2

In [ ]:
arr=np.arange(12).reshape(3,4)
arr
df6=pd.DataFrame(arr)
df6

In [ ]:
score_df=pd.DataFrame(np.random.randint(40,101,size=(10,5)))
score_df

In [ ]:
column_name=['aa','bb','cc','dd','ee']
index_name=['tongxue'+str(i) for  i in range(1,score_df.shape[0]+1)]
index_name
score_df.columns=column_name
score_df.index=index_name
score_df

In [2]:
df=pd.DataFrame({
    'name':[np.nan,'jsljf','fsjf','ubgrng'],
    'age':[3,20,3,5]
})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     4 non-null      int64
dtypes: int64(1), str(1)
memory usage: 212.0 bytes

In [5]:
df2=pd.DataFrame(['2024-03-02'],dtype='datetime64[ns]')
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 140.0 bytes

In [6]:
df3=pd.Series([2,3,5],dtype='category')
df3.info()

<class 'pandas.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      category
dtypes: category(1)
memory usage: 159.0 bytes

In [4]:
df=pd.read_csv('../data/stock_day.csv')
df
data=df.drop(['ma5','ma10','ma20','v_ma5'],axis=1)
data

,open,high,close,low,volume,price_change,p_change,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,46738.65,55576.11,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,42736.34,56007.50,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,41871.97,56372.85,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,39904.78,60149.60,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,42935.74,61716.11,0.58
...,...,...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,115090.18,115090.18,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,98904.79,98904.79,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,100812.93,100812.93,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,117681.67,117681.67,4.76
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,96291.73,96291.73,3.30

In [18]:
data['close']['2018-02-27']

np.float64(24.16)

In [21]:
data.loc['2018-02-27':'2018-02-23',['open','high','close']]

             open   high  close
2018-02-27  23.53  25.88  24.16
2018-02-26  22.80  23.78  23.53
2018-02-23  22.88  23.37  22.82

In [22]:
data.iloc[:3, :5]

             open   high  close    low    volume
2018-02-27  23.53  25.88  24.16  23.53  95578.03
2018-02-26  22.80  23.78  23.53  22.80  60985.11
2018-02-23  22.88  23.37  22.82  22.71  52914.01

In [24]:
data['low'].head()

2018-02-27    23.53
2018-02-26    22.80
2018-02-23    22.71
2018-02-22    22.02
2018-02-14    21.48
Name: low, dtype: float64

In [25]:
data['low']+1

2018-02-27    24.53
2018-02-26    23.80
2018-02-23    23.71
2018-02-22    23.02
2018-02-14    22.48
              ...
2015-03-06    14.13
2015-03-05    13.87
2015-03-04    13.61
2015-03-03    13.52
2015-03-02    13.20
Name: low, Length: 643, dtype: float64

In [26]:
data['low'].head()

2018-02-27    23.53
2018-02-26    22.80
2018-02-23    22.71
2018-02-22    22.02
2018-02-14    21.48
Name: low, dtype: float64

In [29]:
data.open.head()

2018-02-27    23.53
2018-02-26    22.80
2018-02-23    22.88
2018-02-22    22.25
2018-02-14    21.49
Name: open, dtype: float64

In [30]:
data['open'].head()

2018-02-27    23.53
2018-02-26    22.80
2018-02-23    22.88
2018-02-22    22.25
2018-02-14    21.49
Name: open, dtype: float64

In [6]:
data['open']*10

2018-02-27    235.3
2018-02-26    228.0
2018-02-23    228.8
2018-02-22    222.5
2018-02-14    214.9
              ...
2015-03-06    131.7
2015-03-05    128.8
2015-03-04    128.0
2015-03-03    125.2
2015-03-02    122.5
Name: open, Length: 643, dtype: float64

In [7]:
def my_fun(col):
    return col.max()-col.min()
data[['open','close']]
data[['open','close']].apply(my_fun,axis=0)

open     22.74
close    22.85
dtype: float64

In [9]:
from sqlalchemy import create_engine
data=pd.read_csv('../data/csv示例文件.csv', encoding='gbk')
data

   Unnamed: 0    birthday name   AKA
0           0    1960/5/7  刘海柱  职业法师
1           1    1978/9/1  赵金龙   大力哥
2           2  1984/12/27  周立齐  窃格瓦拉
3           3   1969/1/24   于谦  相声皇后

In [10]:
engine=create_engine('mysql+pymysql://root:root@localhost:3306/day01?charset=utf8')

In [13]:
data.to_sql('mytable',engine,if_exists='append',index=False)

4

In [14]:
sql_df=pd.read_sql('mytable',engine)
sql_df

   Unnamed: 0    birthday name   AKA
0           0    1960/5/7  刘海柱  职业法师
1           1    1978/9/1  赵金龙   大力哥
2           2  1984/12/27  周立齐  窃格瓦拉
3           3   1969/1/24   于谦  相声皇后
4           0    1960/5/7  刘海柱  职业法师
5           1    1978/9/1  赵金龙   大力哥
6           2  1984/12/27  周立齐  窃格瓦拉
7           3   1969/1/24   于谦  相声皇后

In [15]:
sql_df=pd.read_sql('select * from mytable',engine)

In [16]:
sql_df

   Unnamed: 0    birthday name   AKA
0           0    1960/5/7  刘海柱  职业法师
1           1    1978/9/1  赵金龙   大力哥
2           2  1984/12/27  周立齐  窃格瓦拉
3           3   1969/1/24   于谦  相声皇后
4           0    1960/5/7  刘海柱  职业法师
5           1    1978/9/1  赵金龙   大力哥
6           2  1984/12/27  周立齐  窃格瓦拉
7           3   1969/1/24   于谦  相声皇后

In [20]:
sql_df.to_csv('../../data/sql_to_csv 260426.csv',index=False,columns=['birthday','name','AKA'])

In [22]:
data=pd.read_json('../data/test.json', orient='records', lines=True)
data

,article_link,headline,is_sarcastic
0,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
1,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
2,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
3,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
4,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0

In [23]:
data.to_json('../../data/test_records.json',orient="records")

In [30]:
df=pd.read_csv('../data/stock_day.csv', usecols=['open']).head()
df

             open
2018-02-27  23.53
2018-02-26  22.80
2018-02-23  22.88
2018-02-22  22.25
2018-02-14  21.49

In [31]:
df['c1']=12
df

             open  c1
2018-02-27  23.53  12
2018-02-26  22.80  12
2018-02-23  22.88  12
2018-02-22  22.25  12
2018-02-14  21.49  12

In [32]:
df['c2']=[i for i in range(5)]
df

             open  c1  c2
2018-02-27  23.53  12   0
2018-02-26  22.80  12   1
2018-02-23  22.88  12   2
2018-02-22  22.25  12   3
2018-02-14  21.49  12   4

In [34]:
df['c3']=df.open*1000
df

             open  c1  c2       c3
2018-02-27  23.53  12   0  23530.0
2018-02-26  22.80  12   1  22800.0
2018-02-23  22.88  12   2  22880.0
2018-02-22  22.25  12   3  22250.0
2018-02-14  21.49  12   4  21490.0

In [36]:
def my_fun():
    return 2500
df['c4']=my_fun()
df

             open  c1  c2       c3    c4
2018-02-27  23.53  12   0  23530.0  2500
2018-02-26  22.80  12   1  22800.0  2500
2018-02-23  22.88  12   2  22880.0  2500
2018-02-22  22.25  12   3  22250.0  2500
2018-02-14  21.49  12   4  21490.0  2500

In [38]:
df3=df.assign(c5=425)
df3

             open  c1  c2       c3    c4   c5
2018-02-27  23.53  12   0  23530.0  2500  425
2018-02-26  22.80  12   1  22800.0  2500  425
2018-02-23  22.88  12   2  22880.0  2500  425
2018-02-22  22.25  12   3  22250.0  2500  425
2018-02-14  21.49  12   4  21490.0  2500  425

In [39]:
df3.assign(
    c11=23,
    c12=[i for i in range(5)],
    c13=df.open*100,
    c14=my_fun()
)

             open  c1  c2       c3    c4   c5  c11  c12     c13   c14
2018-02-27  23.53  12   0  23530.0  2500  425   23    0  2353.0  2500
2018-02-26  22.80  12   1  22800.0  2500  425   23    1  2280.0  2500
2018-02-23  22.88  12   2  22880.0  2500  425   23    2  2288.0  2500
2018-02-22  22.25  12   3  22250.0  2500  425   23    3  2225.0  2500
2018-02-14  21.49  12   4  21490.0  2500  425   23    4  2149.0  2500

In [41]:

df.drop(index=['2018-02-27'])
df

             open  c1  c2       c3    c4
2018-02-27  23.53  12   0  23530.0  2500
2018-02-26  22.80  12   1  22800.0  2500
2018-02-23  22.88  12   2  22880.0  2500
2018-02-22  22.25  12   3  22250.0  2500
2018-02-14  21.49  12   4  21490.0  2500

In [45]:
df.c1.replace('12',"22")
df

             open  c1  c2       c3    c4
2018-02-27  23.53  12   0  23530.0  2500
2018-02-26  22.80  12   1  22800.0  2500
2018-02-23  22.88  12   2  22880.0  2500
2018-02-22  22.25  12   3  22250.0  2500
2018-02-14  21.49  12   4  21490.0  2500

In [11]:
import pandas as pd

df = pd.read_csv('../data/1960-2019全球GDP数据.csv', encoding='gbk')
df2 = df.head()
df2

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [7]:
df2.drop(0)
df2.drop([2,4])

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
3  1960      中国   59716467625

In [13]:
df2.drop(['year'],axis="columns")
# df.drop(columns=['GDP'])
df.drop(['GDP'],axis=1)

      year   country
0     1960        美国
1     1960        英国
2     1960        法国
3     1960        中国
4     1960        日本
...    ...       ...
9925  2019  圣多美和普林西比
9926  2019        帕劳
9927  2019      基里巴斯
9928  2019        瑙鲁
9929  2019       图瓦卢

[9930 rows x 2 columns]

In [16]:
df3=pd.concat([df2,df2])
df3

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [ ]:
df3.drop_duplicates()

In [17]:
df3.country.drop_duplicates()

0    美国
1    英国
2    法国
3    中国
4    日本
Name: country, dtype: str

In [18]:
df3

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [25]:
df3.year.replace(1960,19600)

0    19000
1    19000
2    19000
3    19000
4    19000
0    19000
1    19000
2    19000
3    19000
4    19000
Name: year, dtype: int64

In [21]:
df3

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [24]:
df3.replace({1960:19000},inplace=True)

    year country           GDP
0  19000      美国  543300000000
1  19000      英国   73233967692
2  19000      法国   62225478000
3  19000      中国   59716467625
4  19000      日本   44307342950
0  19000      美国  543300000000
1  19000      英国   73233967692
2  19000      法国   62225478000
3  19000      中国   59716467625
4  19000      日本   44307342950

In [26]:
df3

    year country           GDP
0  19000      美国  543300000000
1  19000      英国   73233967692
2  19000      法国   62225478000
3  19000      中国   59716467625
4  19000      日本   44307342950
0  19000      美国  543300000000
1  19000      英国   73233967692
2  19000      法国   62225478000
3  19000      中国   59716467625
4  19000      日本   44307342950

In [ ]:
df3.rank()

In [ ]:
df3.GDP.rank()