In [ ]:
import pandas as pd
import numpy as np
import random

# series

In [ ]:
#series 一列数据 #dataframe多列数据

## 创建series对象

In [ ]:
#创建series对象，采用默认自增索引
s1=pd.Series([1,2,3,4,5])
print(s1)

In [ ]:
#创建series对象，采用系定义索引
s2=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s2)

In [ ]:
#3.使用字典，元组创建Series对象
#字典
s3=pd.Series({'a':1,'b':2,'c':3})
print(s3)
#元组
s4=pd.Series((11,22,33,44))
print(s4)

In [ ]:
# 4.使用numpy船舰series对象
s5=pd.Series(np.arange(10))
print(s5)

## 2.2 series对象属性

In [ ]:
#1.构建series对象，索引为A-F，职位0-5
s6=pd.Series([0,1,2,3,4,5], index=['a','b','c','d','e','f'])
print(s6)

#列表推导式
s7=pd.Series(data=[i for i in range(6)], index=[i for i in 'abcdef'])
print(s7)

In [ ]:
#2. 获取series对象的索引列的值
print(s7.index)

In [ ]:
#3获取Series对象的 值

print(s7.values)

In [ ]:
#4Series 支持根据索引获取值
print(s7['a'])

In [ ]:
#5.根据索引修改Series的值
s7['b']=666
print(s7)

# DataFrame对象

## 3.1创建DataFrame对象

In [ ]:
#1.通过字典+列表方式实现
#1.1准备数据集，每个键值对=1  列  数据
info={
    'name':['aaa','bbb','ccc'],
    'gender':['male','female','male'],
    'age':[33,44,55]
}
#1.2 封装成DataFrame对象
df1=pd.DataFrame(data=info)
print(df1,type(df1))

In [ ]:
#2. 通过列表+元组方式实现
#1.每个元组=一  行  数据
info=[
    ('aaa','female',33),
    ('bbb','male',66),
    ('ccc','female',66),
]
#2.封装成DataFrame对象
df2=pd.DataFrame(data=info,columns=['name','gender','age'])
print(df2,type(df2))

In [ ]:
#3.通过numpy的ndarray->pandas DataFrame的方式实现
#1.创建numpy的ndarray对象
arr1=np.arange(12).reshape(3,4)
arr1

In [ ]:
#2.封装DataFrame对象
df3=pd.DataFrame(data=arr1,columns=['a','b','c','e'])
df3

### 学生信息处理-》DataFrame简单案例

In [ ]:
#1.生成10名同学，5们功课的成绩范围40~100
score_df=pd.DataFrame(np.random.randint(40,101,(10,5)))
score_df

In [ ]:
#修改DataFrame对象的 列名 索引值
column_name=['语文','数学','英语','政治','体育']
index_name=['同学'+ str(i) for i in range(score_df.shape[0])]
score_df.shape
score_df.shape[0]

#3.具体修改DataFrame对象
score_df.columns=column_name
score_df.index=index_name

#rename函数
# score_df.rename(index={0:'111'},columns={0:'222'},inplace=True)

score_df

## 3.DataFrame的基本属性

In [ ]:
# shape 维度（行列数）
print(score_df.shape)

# index 索引列
print(score_df.index)

# columns 列名
print(score_df.columns)
#data:数据
print(score_df.values)
score_df

In [ ]:
#行列转置 T
score_df.T

## DataFrame的方法

In [ ]:
# 1. head(n) 查看前n行数据 默认5条
score_df.head()

In [ ]:
# 2. tail(n) 查看后n行数据 默认是5条数据
score_df.tail(3)

In [ ]:
# 3. info() 查看df对象的信息
score_df.info()

In [ ]:
# 4. describe() 查看df对象的描述性信息
score_df.describe()

In [ ]:
# 5. reset_index() 重置索引列
score_df.reset_index(drop=True) #

In [ ]:
# 6. set_index() 重新设置索引列
score_df.set_index('语文')
score_df.set_index(['语文','英语'])

## pandas的数据类型

In [ ]:
# pandas中的数据类型基本和python一致
# 特殊 python:str-> pandas:object
# python:None-> pandas:nan,NaN,NAN
#pandas独有category类型，针对于分类数据操作更快

In [ ]:
# 1. 创建DataFrame对象
df=pd.DataFrame({
    'name':['aaa','bbb','ccc','ddd'],
    'gender':['male','female','male', np.nan],
    'age':[33,44,55,77]
})
df

In [ ]:
# 2. 查看df对象的详细信息
df.info()

In [ ]:
# 3. 演示日期类型 datetime
df2=pd.DataFrame(['2025-03-29','2025-03-30','2025-03-31'],dtype='datetime64[ns]')
df2
print(df2.dtypes)

In [ ]:
# 4. 演示 日期查类型 timedelta
start_date=pd.to_datetime('2001-01-24')
end_date=pd.to_datetime('2029-03-27')

print(end_date-start_date)
print(type(end_date - start_date))

In [ ]:
# 5. 演示category类型
s1=pd.Series(['male','female','others'],dtype='category')
print(s1)

## pandas基本数据操作

In [40]:
# 1.读数据
df=pd.read_csv('../data/stock_day.csv')
df

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,22.406,21.955,22.942,40827.52,42736.34,56007.50,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,21.938,21.929,23.022,35119.58,41871.97,56372.85,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,21.446,21.909,23.137,35397.58,39904.78,60149.60,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,21.366,21.923,23.253,33590.21,42935.74,61716.11,0.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,13.112,13.112,13.112,115090.18,115090.18,115090.18,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,12.820,12.820,12.820,98904.79,98904.79,98904.79,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,12.707,12.707,12.707,100812.93,100812.93,100812.93,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,12.610,12.610,12.610,117681.67,117681.67,117681.67,4.76
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,12.520,12.520,12.520,96291.73,96291.73,96291.73,3.30

In [41]:
# 2. 移除不需要的字段
df=df.drop(columns=['ma5','ma10','ma20','v_ma5','v_ma10','v_ma20'])
df

,open,high,close,low,volume,price_change,p_change,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,0.58
...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30

In [ ]:
df.info()

## 索引操作

In [ ]:
# 1. 根据索引获取元素，先列后行
df['open']['2018-02-27']

In [ ]:
# 2. 结合loc 个女就行索引和列名来获取元素
df.loc['2018-02-27','open']

df.iloc[0,0]

#
df.loc['2018-02-27':'2018-02-14',['open','high']]
df.loc['2018-02-27':'2018-02-14','open':'high']

# df.iloc[0:5,[0,1]]
# df.iloc[0:5,0:2]

In [ ]:
# 2. 赋值操作
df['open']=23
df.close=1 #
df

## 4.4 排序操作

In [ ]:
# 升序
df.sort_values(by='high',ascending=True)

In [ ]:
# 基于high和low ，
df.sort_values(by=['high','low'],ascending=[False,False])

In [ ]:
# 按照索引排序
df.sort_index(ascending=True)

In [ ]:
# 演示Series对象，也有sort_index()排序方法
df.open

# DtaFrame的运算

In [ ]:
df

In [ ]:
# 2. 针对close的值+2

df['close']+2
df.close.add(2)

## 逻辑运算符

In [42]:
df

,open,high,close,low,volume,price_change,p_change,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,0.58
...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30

In [44]:
# 筛选出open》23的数据
df[df.open>23]

# 帅选出open》23 且《24的数据
df[(df.open>23) & (df.open<24)]

,open,high,close,low,volume,price_change,p_change,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39
2018-02-01,23.71,23.86,22.42,22.22,66414.64,-1.30,-5.48,1.66
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,1.23
2018-01-30,23.71,24.08,23.83,23.70,32420.43,0.05,0.21,0.81
2018-01-16,23.40,24.60,24.40,23.30,101295.42,0.96,4.10,2.54
2018-01-12,23.70,25.15,24.24,23.42,120303.53,0.56,2.37,3.01
2018-01-11,23.67,23.85,23.67,23.21,48525.75,-0.12,-0.50,1.21
2017-12-22,23.21,23.39,22.99,22.90,28394.00,-0.21,-0.91,0.71
2017-12-21,23.39,23.50,23.21,22.86,34005.55,-0.11,-0.47,0.85
2017-12-20,23.61,23.96,23.33,23.20,43368.92,-0.14,-0.60,1.09
2017-12-19,23.23,23.66,23.46,23.23,43068.70,0.31,1.34,1.08
2017-12-15,23.40,23.40,23.00,22.85,43442.15,-0.46,-1.96,1.09
2017-12-14,23.65,23.77,23.47,23.22,45061.12,-0.33,-1.39,1.13
2017-12-13,23.99,24.38,23.81,23.60,68659.12,-0.15,-0.63,1.72
2017-12-04,23.91,24.15,22.92,22.85,85482.80,-1.27,-5.25,2.14
2017-09-06,23.51,24.88,24.51,23.38,161732.80,0.56,2.34,4.05
2017-09-05,23.76,24.32,23.95,23.31,138987.19,0.19,0.80,3.48
2017-08-30,23.25,24.60,24.15,23.21,196509.73,1.09,4.73,4.92
2017-08-29,23.45,23.85,23.06,23.04,90952.18,-0.44,-1.87,2.28
2017-08-28,23.45,23.70,23.50,23.05,119146.78,0.13,0.56,2.98
2017-08-23,23.90,24.06,23.07,22.85,264518.94,-1.28,-5.26,6.62
2017-07-27,23.39,23.39,22.76,22.63,101811.01,-0.64,-2.73,2.55
2017-07-26,23.53,23.92,23.40,22.85,110276.48,-0.30,-1.27,2.76
2017-07-25,23.07,24.20,23.70,22.64,167489.48,0.67,2.91,4.19
2017-07-14,23.28,24.29,22.87,22.80,163954.17,-0.60,-2.56,4.10
2017-07-13,23.60,23.60,23.47,22.81,175621.84,-0.34,-1.43,4.40
2017-06-27,23.10,23.24,22.20,22.06,288556.75,-1.06,-4.56,7.22
2017-06-26,23.30,23.87,23.26,22.57,282271.66,-0.08,-0.34,7.06
2017-06-22,23.32,25.93,25.93,23.26,421673.59,2.36,10.01,10.55
2017-06-20,23.75,24.45,24.08,22.22,374005.34,1.58,7.02,9.36
2016-11-08,23.17,24.50,24.46,22.95,105850.97,1.41,6.12,2.65
2016-11-07,23.11,23.39,23.06,22.84,44069.47,-0.33,-1.41,1.10
2016-11-04,23.17,23.65,23.30,22.80,57950.55,0.09,0.39,1.45
2016-11-03,23.16,23.51,23.20,22.65,108786.66,0.13,0.56,2.72
2016-11-02,23.80,23.99,23.10,23.00,105628.11,-0.78,-3.27,2.64
2016-10-31,23.78,24.75,24.27,23.51,150868.73,0.38,1.59,3.78
2016-10-27,23.89,24.28,24.02,23.89,95846.80,-0.08,-0.33,2.40
2016-10-26,23.25,24.56,24.10,22.80,151046.05,0.86,3.70,3.78
2016-09-09,23.92,24.06,23.08,22.60,182559.94,-1.14,-4.71,6.25
2016-09-07,23.20,24.94,24.48,23.00,228627.59,1.49,6.48,7.83
2015-12-28,23.20,23.40,21.89,21.85,71790.53,-1.31,-5.65,2.46
2015-12-25,23.18,23.30,23.19,22.82,46800.90,0.15,0.65,1.60
2015-12-23,23.97,24.44,24.11,23.66,70107.29,0.33,1.39,2.40
2015-12-22,23.80,24.10,23.80,23.50,53460.38,-0.11,-0.46,1.83
2015-12-18,23.53,24.66,23.99,23.43,109230.05,0.65,2.79,3.74
2015-11-27,23.35,23.43,21.17,21.17,96648.60,-2.35,-9.99,3.31
2015-11-26,23.85,24.08,23.53,23.50,51446.29,-0.31,-1.30,1.76
2015-11-25,23.40,24.15,23.85,23.40,67009.81,0.23,0.97,2.29
2015-11-24,23.26,23.75,23.64,22.86,65186.31,0.33,1.42,2.23
2015-11-20,23.93,24.49,24.23,23.53,101795.66,0.32,1.34,3.48
2015-11-19,23.72,24.26,23.91,23.01,120660.59,-0.12,-0.50,4.13
2015-11-10,23.50,24.79,24.79,23.50,202020.19,2.25,9.98,6.92
2015-10-26,23.32,23.46,21.85,21.06,178488.00,-0.58,-2.59,6.11
2015-07-23,23.20,24.26,24.14,23.00,141147.69,1.68,7.48,4.83
2015-06-30,23.82,25.13,25.01,21.44,174521.44,1.19,5.00,5.97
2015-05-19,23.68,23.69,23.32,22.47,82945.73,0.25,1.08,2.84
2015-04-15,23.45,25.56,24.38,23.40,250311.59,1.14,4.91,8.57

In [49]:
# 通过query（）
df.query('open>23& open<24')

,open,high,close,low,volume,price_change,p_change,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39
2018-02-01,23.71,23.86,22.42,22.22,66414.64,-1.30,-5.48,1.66
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,1.23
2018-01-30,23.71,24.08,23.83,23.70,32420.43,0.05,0.21,0.81
2018-01-16,23.40,24.60,24.40,23.30,101295.42,0.96,4.10,2.54
2018-01-12,23.70,25.15,24.24,23.42,120303.53,0.56,2.37,3.01
2018-01-11,23.67,23.85,23.67,23.21,48525.75,-0.12,-0.50,1.21
2017-12-22,23.21,23.39,22.99,22.90,28394.00,-0.21,-0.91,0.71
2017-12-21,23.39,23.50,23.21,22.86,34005.55,-0.11,-0.47,0.85
2017-12-20,23.61,23.96,23.33,23.20,43368.92,-0.14,-0.60,1.09
2017-12-19,23.23,23.66,23.46,23.23,43068.70,0.31,1.34,1.08
2017-12-15,23.40,23.40,23.00,22.85,43442.15,-0.46,-1.96,1.09
2017-12-14,23.65,23.77,23.47,23.22,45061.12,-0.33,-1.39,1.13
2017-12-13,23.99,24.38,23.81,23.60,68659.12,-0.15,-0.63,1.72
2017-12-04,23.91,24.15,22.92,22.85,85482.80,-1.27,-5.25,2.14
2017-09-06,23.51,24.88,24.51,23.38,161732.80,0.56,2.34,4.05
2017-09-05,23.76,24.32,23.95,23.31,138987.19,0.19,0.80,3.48
2017-08-30,23.25,24.60,24.15,23.21,196509.73,1.09,4.73,4.92
2017-08-29,23.45,23.85,23.06,23.04,90952.18,-0.44,-1.87,2.28
2017-08-28,23.45,23.70,23.50,23.05,119146.78,0.13,0.56,2.98
2017-08-23,23.90,24.06,23.07,22.85,264518.94,-1.28,-5.26,6.62
2017-07-27,23.39,23.39,22.76,22.63,101811.01,-0.64,-2.73,2.55
2017-07-26,23.53,23.92,23.40,22.85,110276.48,-0.30,-1.27,2.76
2017-07-25,23.07,24.20,23.70,22.64,167489.48,0.67,2.91,4.19
2017-07-14,23.28,24.29,22.87,22.80,163954.17,-0.60,-2.56,4.10
2017-07-13,23.60,23.60,23.47,22.81,175621.84,-0.34,-1.43,4.40
2017-06-27,23.10,23.24,22.20,22.06,288556.75,-1.06,-4.56,7.22
2017-06-26,23.30,23.87,23.26,22.57,282271.66,-0.08,-0.34,7.06
2017-06-22,23.32,25.93,25.93,23.26,421673.59,2.36,10.01,10.55
2017-06-20,23.75,24.45,24.08,22.22,374005.34,1.58,7.02,9.36
2016-11-08,23.17,24.50,24.46,22.95,105850.97,1.41,6.12,2.65
2016-11-07,23.11,23.39,23.06,22.84,44069.47,-0.33,-1.41,1.10
2016-11-04,23.17,23.65,23.30,22.80,57950.55,0.09,0.39,1.45
2016-11-03,23.16,23.51,23.20,22.65,108786.66,0.13,0.56,2.72
2016-11-02,23.80,23.99,23.10,23.00,105628.11,-0.78,-3.27,2.64
2016-10-31,23.78,24.75,24.27,23.51,150868.73,0.38,1.59,3.78
2016-10-27,23.89,24.28,24.02,23.89,95846.80,-0.08,-0.33,2.40
2016-10-26,23.25,24.56,24.10,22.80,151046.05,0.86,3.70,3.78
2016-09-09,23.92,24.06,23.08,22.60,182559.94,-1.14,-4.71,6.25
2016-09-07,23.20,24.94,24.48,23.00,228627.59,1.49,6.48,7.83
2015-12-28,23.20,23.40,21.89,21.85,71790.53,-1.31,-5.65,2.46
2015-12-25,23.18,23.30,23.19,22.82,46800.90,0.15,0.65,1.60
2015-12-23,23.97,24.44,24.11,23.66,70107.29,0.33,1.39,2.40
2015-12-22,23.80,24.10,23.80,23.50,53460.38,-0.11,-0.46,1.83
2015-12-18,23.53,24.66,23.99,23.43,109230.05,0.65,2.79,3.74
2015-11-27,23.35,23.43,21.17,21.17,96648.60,-2.35,-9.99,3.31
2015-11-26,23.85,24.08,23.53,23.50,51446.29,-0.31,-1.30,1.76
2015-11-25,23.40,24.15,23.85,23.40,67009.81,0.23,0.97,2.29
2015-11-24,23.26,23.75,23.64,22.86,65186.31,0.33,1.42,2.23
2015-11-20,23.93,24.49,24.23,23.53,101795.66,0.32,1.34,3.48
2015-11-19,23.72,24.26,23.91,23.01,120660.59,-0.12,-0.50,4.13
2015-11-10,23.50,24.79,24.79,23.50,202020.19,2.25,9.98,6.92
2015-10-26,23.32,23.46,21.85,21.06,178488.00,-0.58,-2.59,6.11
2015-07-23,23.20,24.26,24.14,23.00,141147.69,1.68,7.48,4.83
2015-06-30,23.82,25.13,25.01,21.44,174521.44,1.19,5.00,5.97
2015-05-19,23.68,23.69,23.32,22.47,82945.73,0.25,1.08,2.84
2015-04-15,23.45,25.56,24.38,23.40,250311.59,1.14,4.91,8.57

In [55]:
# 固定值的筛选 isin
# 查询open价格为23.53  23.85
df.query('open in [23.53 , 23.85]')
df[df["open"].isin([23.53, 23.85])]

,open,high,close,low,volume,price_change,p_change,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,1.23
2017-07-26,23.53,23.92,23.40,22.85,110276.48,-0.30,-1.27,2.76
2015-12-18,23.53,24.66,23.99,23.43,109230.05,0.65,2.79,3.74
2015-11-26,23.85,24.08,23.53,23.50,51446.29,-0.31,-1.30,1.76

## 统计函数·

In [63]:
# count(),mean(),median(),min(),std(),var()
df.count()
df.mean()
df.median()
df.min()
df.std()
df.var()

open            1.545255e+01
high            1.662665e+01
close           1.554572e+01
low             1.437902e+01
volume          5.458124e+09
price_change    8.072595e-01
p_change        1.664394e+01
turnover        4.323800e+00
dtype: float64

In [71]:
#apply() 自定义函数
#df.apply(自定义函数，axis=0）


#同时获取到多列的最大值和最小值的差值, open close
#1. 分解
def my_fun(col):
    return col.max()-col.min()
#2.通过apply（）调用函数，作用到指定的列
df[['open','close']].apply(my_fun,axis=0)
df[['open','close']].apply(my_fun,axis=1)



#lambda表达式
df[['open','close']].apply(lambda x: x.max()-x.min())

open     22.74
close    22.85
dtype: float64