In [ ]:
import numpy as np
import pandas as pd
import os

from dask.dataframe import to_json
from sqlalchemy import create_engine
from toolz import drop

# 操作csv文件

In [ ]:
df=pd.read_csv('../data/stock_day.csv',sep=',',usecols=['open','high','low','close','volume'])
df

In [ ]:
df[:10].to_csv('../data/stock_day_write.csv')

In [ ]:
# tsv ->特殊的csv文件 ，以tab键分割
df[:5].to_csv('../data/stock_day_write.tsv',sep='\t',index=True)

In [ ]:
#读取tsv文件
df=pd.read_csv(filepath_or_buffer='../data/stock_day_write.tsv',sep='\t',index_col=0)

# 操作Mysql数据表

In [ ]:
# 需要pymysql+sqlalchemy

data=pd.read_csv('../data/csv示例文件.csv',encoding='gbk',index_col=0)
data

In [ ]:
#1. 创建引擎
                                    #用户名：密码@链接ip：端口号/数据库
engin=create_engine('mysql+pymysql://root:root@localhost:3306/day01?charset=utf8')

#2. 向数据库写入
#
data.to_sql('panda01',engin,if_exists='append',index=False)
print('scc')

In [ ]:
# 读取sql
sql_df=pd.read_sql('panda01',con=engin)
sql_df=pd.read_sql('select name from panda01 limit 3',con=engin)
sql_df

# 操作json文件

In [ ]:
#1. 读取json文件
df=pd.read_json('../data/test.json',orient='records',lines=True)
df

In [ ]:
# 2. 写入json

df.to_json('../data/test_write.json',orient='records',lines=True)
df.to_json('../data/test_write2.json')
df.to_json('../data/test_write3.json',orient='index')

print('scc')

# pandas增删改查

## 增

In [ ]:
df=pd.read_csv('..//data/1960-2019全球GDP数据.csv',encoding='gbk',)
df2=df[:5].copy()
df2

In [ ]:
#新增列
#1. 直接沟通过赋值方式新增1列
df2['c1']=23
df2['c2']=['aaa','bbb','ccc','ddd','eee']
df2['c3']=df2.year*2
def my_fun():
    return 2999
df2['c4']=my_fun()
df2

In [ ]:
# 2. 使用assign函数
df2.assign(
    c1=23,
    c2=['aaa','bbb','ccc','ddd','eee'],
    c3=df2.year*3,
    c4=my_fun()
)

## 删

In [ ]:
df5=df[:5].copy()
df5

In [ ]:
# 1. 删除行
# df5=df5.drop(index=[1,2,3])
# df5=df5.drop(index=[1,2,3],inplace=True)
# del df5['year']
df5

In [ ]:
# 5.去重
#拼接
df6=pd.concat([df5,df5])
df6.drop_duplicates(inplace=True)
df6

## 改

In [ ]:
df7=df[:5].copy()
df7

In [ ]:
# 1. 新增一列
df7['c1']=23
df7

In [ ]:
# 2 修改GDP的值
df7['GDP']=[1,2,3,4,5]
df7

In [ ]:
# 3 replace()替换
df7.replace('美国','use')

## 查

In [ ]:
df.head()

In [40]:
df['year']

0       1960
1       1960
2       1960
3       1960
4       1960
        ...
9925    2019
9926    2019
9927    2019
9928    2019
9929    2019
Name: year, Length: 9930, dtype: int64

In [ ]:
df[['year']]

In [ ]:
df.year

In [ ]:
# 通过query（）函数，结合条件获取
#查询中美日三国2015-2019的数据
df.query('country in["中国","美国","日本"] and (year>=2015 and year<=2019)')


# df.query('country in["中国","美国","日本"] and year in[2015,2015,1017,2018,1019]')

In [ ]:
# rank()函数，类似于sql的窗口函数

In [65]:
df7=pd.DataFrame({
    '姓名':['胜多负少','挤一挤','路口','ioii'],
    '成绩':[100,44,44,55]
})

In [41]:
df7.rank()

    姓名   成绩
0  1.0  5.0
1  2.0  1.0
2  3.0  2.0
3  4.0  3.0
4  5.0  4.0

In [66]:

df7['成绩排名_min']=df7['成绩'].rank(method='min',ascending=False)
df7['成绩排名_max']=df7['成绩'].rank(method='min',ascending=False)
df7['成绩排名_dense']=df7['成绩'].rank(method='dense',ascending=False)
df7['成绩排名_avg']=df7['成绩'].rank(method='average',ascending=False)
df7['成绩排名_moren ']=df7['成绩'].rank(ascending=False)
df7

     姓名   成绩  成绩排名_min  成绩排名_max  成绩排名_dense  成绩排名_avg  成绩排名_moren
0  胜多负少  100       1.0       1.0         1.0       1.0          1.0
1   挤一挤   44       3.0       3.0         3.0       3.5          3.5
2    路口   44       3.0       3.0         3.0       3.5          3.5
3  ioii   55       2.0       2.0         2.0       2.0          2.0