In [2]:
import numpy as np
import pandas as pd
import os

# 1.空值处理

In [ ]:
# 1. 读取数据
movie_df=pd.read_csv('../data/movie.csv')
movie_df

In [ ]:
# 2. 查看数据介绍
movie_df.columns
movie_df.info()
movie_df.dropna()

In [ ]:
#判断数据是否为空
pd.isnull(movie_df)# 判断数值是否为空，空则True
pd.notnull(movie_df)# 非空为True

np.all(pd.notnull(movie_df))

In [ ]:
# 4.填充缺失值
# movie_df.fillna(23).info()

m1=movie_df['Revenue (Millions)'].fillna(movie_df['Revenue (Millions)'].mean())
m1.info()

In [ ]:
#5. 循环填充缺失值
for col_name in movie_df.columns:
    # print(np.all(pd.notnull(movie_df[col_name]))==False)
    if np.all(pd.notnull(movie_df[col_name]))==False:
        print(col_name)
        print(movie_df[col_name].mean())
        # movie_df[col_name].fillna(movie_df[col_name].mean(),inplace=True)
        movie_df[col_name].fillna({col_name:movie_df[col_name].mean()})

movie_df.info()

In [ ]:
for col_name in movie_df.columns:
    # 检查列中是否有缺失值
    if not np.all(pd.notnull(movie_df[col_name])):
        print(col_name)
        mean_value = movie_df[col_name].mean()
        print(mean_value)
        # 避免链式赋值，直接赋值给原DataFrame
        movie_df[col_name] = movie_df[col_name].fillna(mean_value)

movie_df.info()

## 遇到不是nan的缺失值，修改方法

In [ ]:
# 背景：实际开发中，回到 ? 表示缺失值，如何删除？
#思路 1.转换 2.删除
#? -> nan ->删除

In [ ]:
wis = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data")
wis

In [ ]:
#2. 尝试直接删除缺失值
wis.dropna()

In [ ]:
# 3.
wis.replace('?',np.nan).dropna()

# 2.数据合并

In [ ]:
df=pd.read_csv('../data/1960-2019全球GDP数据.csv',encoding='gbk')
df
df1=df[:10]
df2=df[10:20]

In [ ]:
#2. 通过concat()

pd.concat([df1,df2] ,axis=1)

In [3]:
#2.2merge()->只能行合并（水平合并）

df1=pd.DataFrame({
    'Key1':['k0','k0','k1','k2'],
    'Key2':['k0','k1','k0','k1'],
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3']
})

df2=pd.DataFrame({
    'Key1':['k0','k1','k1','k2'],
    'Key2':['k0','k0','k0','k0'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']
})

In [5]:
#演示merge默认合并方式
pd.merge(df1,df2)
pd.merge(df1,df2,on=['Key1','Key2'],how='inner')

  Key1 Key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k0  A2  B2  C1  D1
2   k1   k0  A2  B2  C2  D2

In [8]:
# 内连接，指定合并字段
pd.merge(df1,df2,on='Key2',how='inner')

  Key1_x Key2   A   B Key1_y   C   D
0     k0   k0  A0  B0     k0  C0  D0
1     k0   k0  A0  B0     k1  C1  D1
2     k0   k0  A0  B0     k1  C2  D2
3     k0   k0  A0  B0     k2  C3  D3
4     k1   k0  A2  B2     k0  C0  D0
5     k1   k0  A2  B2     k1  C1  D1
6     k1   k0  A2  B2     k1  C2  D2
7     k1   k0  A2  B2     k2  C3  D3

# 分组聚合groupby

In [9]:
df=pd.read_csv('../data/uniqlo.csv')
df

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
0,658,深圳,线下,Female,25-29,Weekday,当季新品,4,796.0,4,4,59
1,146,杭州,线下,Female,25-29,Weekday,运动,1,149.0,1,1,49
2,70,深圳,线下,Male,>=60,Weekday,T恤,2,178.0,2,2,49
3,658,深圳,线下,Female,25-29,Weekday,T恤,1,59.0,1,1,49
4,229,深圳,线下,Male,20-24,Weekend,袜子,2,65.0,2,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...
22288,146,杭州,线下,Female,30-34,Weekday,短裤,1,80.0,1,2,19
22289,430,成都,线下,Female,25-29,Weekend,T恤,1,79.0,1,1,49
22290,449,武汉,线下,Female,35-39,Weekday,T恤,1,158.0,1,2,49
22291,758,杭州,线下,Female,20-24,Weekday,袜子,1,26.0,1,1,9
22292,616,成都,线下,Male,30-34,Weekday,当季新品,1,79.0,1,1,59

In [ ]:
#agg->aggregate聚合
#格式：df.groupby(['分组字段1','分组字段2',....]).agg({'列名1':'聚合函数名','列名2':'集合函数名',...})

In [11]:
# 1. 按照名单列分组
df.groupby(['city'])
df.groupby('city')

In [13]:
#2.按照多列分组
df.groupby(['city','channel'])

In [15]:
df.groupby(['city','channel']).get_group(('北京','线下'))

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
9,21,北京,线下,Female,45-49,Weekend,毛衣,1,199.00,1,1,99
168,21,北京,线下,Female,35-39,Weekday,毛衣,3,447.00,3,3,99
175,21,北京,线下,Female,45-49,Weekend,配件,1,149.00,1,1,29
263,21,北京,线下,Male,20-24,Weekday,T恤,1,55.33,1,1,49
289,21,北京,线下,Female,35-39,Weekend,牛仔裤,1,199.00,1,1,69
...,...,...,...,...,...,...,...,...,...,...,...,...
22037,21,北京,线下,Female,20-24,Weekday,T恤,7,493.00,7,7,49
22110,21,北京,线下,Male,50-54,Weekend,当季新品,1,79.00,1,1,59
22192,21,北京,线下,Female,20-24,Weekday,T恤,7,693.00,7,7,49
22273,21,北京,线下,Female,20-24,Weekday,当季新品,2,288.00,2,2,59
22280,21,北京,线下,Female,35-39,Weekend,T恤,1,59.00,1,1,49

In [18]:
#4. 分组+聚合
#根据城市和销售渠道分组，计算销售金额
df.groupby(['city','channel']).agg({'revenue':'sum'})
df.groupby(['city','channel']).aggregate({'revenue':'sum'})

df.groupby(['city','channel']).agg({'revenue':'sum','order':'sum'})

                revenue  order
city channel
上海   线上       114438.09   1237
     线下       275383.64   2800
北京   线下       130458.62   1303
南京   线下       123150.93   1113
广州   线上       200893.30   2115
     线下       117231.19   1277
成都   线下       208189.86   2263
杭州   线下       589518.49   6196
武汉   线上       281420.73   2895
     线下       308357.05   3101
深圳   线下       733123.68   7475
西安   线上        30088.01    325
     线下       180686.61   1954
重庆   线上        26330.35    251
     线下       237162.30   2523

## 分组过滤

In [19]:
#按照城市分组，查询每组销售金额平均值》200的全部数据
df.groupby('city').revenue.mean()

city
上海    163.037110
北京    226.098128
南京    246.301860
广州    145.395105
成都    136.160798
杭州    155.751252
武汉    165.342803
深圳    167.993511
西安    131.323751
重庆    147.449720
Name: revenue, dtype: float64

In [20]:
df.groupby('city').filter(lambda x:x.revenue.mean()>200).city

9        北京
23       南京
40       南京
62       南京
168      北京
         ..
22182    南京
22192    北京
22251    南京
22273    北京
22280    北京
Name: city, Length: 1077, dtype: str

# 交叉表

In [24]:
data={
    '性别':['男','女','男','女','男','女','男','女'],
    '购买':['是','否','是','否','是','否','是','否',]
}
df=pd.DataFrame(data)

#创建交叉表
crosstab=pd.crosstab(df['性别'],df['购买'])
print(crosstab)

购买  否  是
性别
女   4  0
男   0  4

In [28]:
#2.用透视表完成上述的需求
data={
    '性别':['男','女','男','女','男','女','男','女'],
    '购买':['是','否','是','否','是','否','是','否',],
    '金额':[100,150,200,130,160,220,204,894]
}
df=pd.DataFrame(data)
df.pivot_table(index='性别',columns='购买',values='金额',aggfunc="mean")

购买      否      是
性别
女   348.5    NaN
男     NaN  166.0

In [35]:
# 透视表案例：
df=pd.read_csv('../data/uniqlo.csv')
df

# df.groupby(['city','channel']).agg({'revenue':'sum'})
# df.groupby(['city','channel'],as_index=False).agg({'revenue':'sum'})

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
0,658,深圳,线下,Female,25-29,Weekday,当季新品,4,796.0,4,4,59
1,146,杭州,线下,Female,25-29,Weekday,运动,1,149.0,1,1,49
2,70,深圳,线下,Male,>=60,Weekday,T恤,2,178.0,2,2,49
3,658,深圳,线下,Female,25-29,Weekday,T恤,1,59.0,1,1,49
4,229,深圳,线下,Male,20-24,Weekend,袜子,2,65.0,2,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...
22288,146,杭州,线下,Female,30-34,Weekday,短裤,1,80.0,1,2,19
22289,430,成都,线下,Female,25-29,Weekend,T恤,1,79.0,1,1,49
22290,449,武汉,线下,Female,35-39,Weekday,T恤,1,158.0,1,2,49
22291,758,杭州,线下,Female,20-24,Weekday,袜子,1,26.0,1,1,9
22292,616,成都,线下,Male,30-34,Weekday,当季新品,1,79.0,1,1,59

In [36]:
#透视 作用：统计分组数据，简化分组聚合写法
#index指定分组字段  columns指定分组字段  values指定聚合字段aggfunc指定聚合函数
df.pivot_table(index='city',columns='channel',values='revenue',aggfunc="sum")

channel         线上         线下
city
上海       114438.09  275383.64
北京             NaN  130458.62
南京             NaN  123150.93
广州       200893.30  117231.19
成都             NaN  208189.86
杭州             NaN  589518.49
武汉       281420.73  308357.05
深圳             NaN  733123.68
西安        30088.01  180686.61
重庆        26330.35  237162.30