In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib as plt

In [3]:
#1.加载数据集
house_df=pd.read_csv('../data/LJdata.csv')
house_df

      区域        小区名称     户型     面积(㎡)  价格(元/月)
0     东城     万国城MOMA   1室0厅   59.11平米    10000
1     东城    北官厅胡同2号院   3室0厅   56.92平米     6000
2     东城       和平里三区   1室1厅   40.57平米     6900
3     东城        菊儿胡同   2室1厅   57.09平米     8000
4     东城  交道口北二条35号院   1室1厅   42.67平米     5500
...   ..         ...    ...       ...      ...
8218  顺义        怡馨家园   3室1厅  114.03平米     5500
8219  顺义      旭辉26街区  4房间2卫      59平米     5000
8220  顺义     前进花园玉兰苑   3室1厅   92.41平米     5800
8221  顺义        双裕小区   2室1厅   71.81平米     4200
8222  顺义       樱花园二区   1室1厅   35.43平米     2700

[8223 rows x 5 columns]

In [4]:
#修改列名为英文
house_df.columns=['area','community','house type','aream2','price']
house_df

     area   community house type    aream2  price
0      东城     万国城MOMA       1室0厅   59.11平米  10000
1      东城    北官厅胡同2号院       3室0厅   56.92平米   6000
2      东城       和平里三区       1室1厅   40.57平米   6900
3      东城        菊儿胡同       2室1厅   57.09平米   8000
4      东城  交道口北二条35号院       1室1厅   42.67平米   5500
...   ...         ...        ...       ...    ...
8218   顺义        怡馨家园       3室1厅  114.03平米   5500
8219   顺义      旭辉26街区      4房间2卫      59平米   5000
8220   顺义     前进花园玉兰苑       3室1厅   92.41平米   5800
8221   顺义        双裕小区       2室1厅   71.81平米   4200
8222   顺义       樱花园二区       1室1厅   35.43平米   2700

[8223 rows x 5 columns]

In [7]:
#1.查看数据前5行
house_df.head()
#2.查看列数据分布
house_df.info()
#3.查看列统计指标
house_df.describe(include='all')#统计所有数据包括字符串
house_df.describe()# 默认只统计数值型数据
#4. 查看数据形状
house_df.shape

<class 'pandas.DataFrame'>
RangeIndex: 8223 entries, 0 to 8222
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   area        8223 non-null   str
 1   community   8223 non-null   str
 2   house type  8223 non-null   str
 3   aream2      8223 non-null   str
 4   price       8223 non-null   int64
dtypes: int64(1), str(4)
memory usage: 643.4 KB

               price
count    8223.000000
mean     9512.297823
std      9186.752612
min       566.000000
25%      4800.000000
50%      6800.000000
75%     10000.000000
max    150000.000000

- 需求开始

In [ ]:
#1.找到租金最低，最高的刚子
#2.找到最近新上的10套房源
#3。查看所有跟新时间
#4.查看看房人数的品均值，最大值，最小值
#5. 查看不同看房人数的房源数量，
#6.查看看房人数最多的朝向
#7找到看房人数最多的朝向
#8查找最受欢迎的房型
#9.查找房子的平均租房价格
#10. 找到出租房最多的小区